# Database Configuration
db:
  host: mysql
  port: 3306
  user: root
  password: password
  name: ecommerce

# Kafka Configuration
kafka:
  brokers: kafka:29092
  topic: orders

# RabbitMQ Configuration
rabbitmq:
  host: rabbitmq
  port: 5672
  user: guest
  password: guest

# Service Configuration
services:
  product:
    port: 8080
  order:
    port: 8081 